// AI業界 相関図データ
// threads.html（ストーリースレッド）が描画する。毎週土曜の定期実行で直近1週間のニュースから追記される。
// B-002（2026-07-18 判断済）: 全体相関図は廃止し、スレッド別ミニ図として描画する。
//
// nodes: { id, label, sector, sub?, jp? }
//   sector: "lab"(AIラボ) / "cloud"(ビッグテック・クラウド) / "semi"(半導体) / "app"(応用・スタートアップ) / "invest"(投資家・ファンド)
//   sub:    sector="semi" のみ。"design"(設計) / "fab"(製造) / "memdev"(メモリ・装置)
//   jp:     日本企業なら true（図では日の丸印）
// edges: { from, to, type, threads, label, date, source, flow?, status?, amount?, person? }
//   type:    invest(出資・調達) / partner(提携・供給) / talent(人材移籍) / ma(買収・合併)
//   threads: このエッジが属するストーリースレッドのid配列（threads_data.js 参照）。
//            compute / labs / china / japan / semi / talent。どのスレッドにも属さない関係は [] でよい
//            （スレッドに関係ない業界ニュースを無理に収録する義務はない — 網羅はしない）
//   flow:    type="partner" のみ。何が流れる関係か: "計算資源" / "資金" / "モデル" / "販売" / "技術"
//   status:  省略時 "official"(公式発表)。"reported"(報道ベース) / "negotiating"(交渉中・未確定) / "ended"(終了した関係)
//   amount:  type="invest" のみ。金額（億ドル・概算）。非公表・不明なら null
//   person:  type="talent" のみ。移籍した人物名（人材は人物単位で1エッジ。同じ企業ペアの複数エッジ可）
//   source:  出典URL（全エッジ必須）。古い関係も履歴として残す（削除しない）。
window.RELATIONS = {
  updated: "2026-07-20",
  nodes: [
    // AIラボ
    { id: "openai",       label: "OpenAI",       sector: "lab" },
    { id: "anthropic",    label: "Anthropic",    sector: "lab" },
    { id: "xai",          label: "xAI",          sector: "lab" },
    { id: "deepseek",     label: "DeepSeek",     sector: "lab" },
    { id: "mistral",      label: "Mistral AI",   sector: "lab" },
    { id: "ami",          label: "AMI Labs",     sector: "lab" },
    { id: "sakana",       label: "Sakana AI",    sector: "lab", jp: true },
    { id: "reflectionai", label: "Reflection AI", sector: "lab" },
    { id: "moonshot",     label: "Moonshot AI",  sector: "lab" },
    // ビッグテック・クラウド
    { id: "microsoft",    label: "Microsoft",    sector: "cloud" },
    { id: "google",       label: "Google",       sector: "cloud" },
    { id: "amazon",       label: "Amazon",       sector: "cloud" },
    { id: "meta",         label: "Meta",         sector: "cloud" },
    { id: "apple",        label: "Apple",        sector: "cloud" },
    { id: "ibm",          label: "IBM",          sector: "cloud" },
    { id: "tencent",      label: "Tencent",      sector: "cloud" },
    { id: "oracle",       label: "Oracle",       sector: "cloud" },
    { id: "nebius",       label: "Nebius",       sector: "cloud" },
    { id: "alibaba",      label: "Alibaba",      sector: "cloud" },
    { id: "bytedance",    label: "ByteDance",    sector: "cloud" },
    { id: "terawulf",     label: "TeraWulf",     sector: "cloud" },
    // 半導体
    { id: "nvidia",       label: "NVIDIA",       sector: "semi", sub: "design" },
    { id: "amd",          label: "AMD",          sector: "semi", sub: "design" },
    { id: "broadcom",     label: "Broadcom",     sector: "semi", sub: "design" },
    { id: "qualcomm",     label: "Qualcomm",     sector: "semi", sub: "design" },
    { id: "cerebras",     label: "Cerebras",     sector: "semi", sub: "design" },
    { id: "tenstorrent",  label: "Tenstorrent",  sector: "semi", sub: "design" },
    { id: "huawei",       label: "Huawei",       sector: "semi", sub: "design" },
    { id: "intel",        label: "Intel",        sector: "semi", sub: "fab" },
    { id: "tsmc",         label: "TSMC",         sector: "semi", sub: "fab" },
    { id: "samsung",      label: "Samsung",      sector: "semi", sub: "fab" },
    { id: "rapidus",      label: "Rapidus",      sector: "semi", sub: "fab", jp: true },
    { id: "skhynix",      label: "SK hynix",     sector: "semi", sub: "memdev" },
    { id: "asml",         label: "ASML",         sector: "semi", sub: "memdev" },
    { id: "micron",       label: "Micron",       sector: "semi", sub: "memdev" },
    // 応用・スタートアップ
    { id: "spacex",       label: "SpaceX",           sector: "app" },
    { id: "scaleai",      label: "Scale AI",         sector: "app" },
    { id: "cursor",       label: "Cursor (Anysphere)", sector: "app" },
    { id: "stainless",    label: "Stainless",        sector: "app" },
    { id: "coefficient",  label: "Coefficient Bio",  sector: "app" },
    { id: "astral",       label: "Astral",           sector: "app" },
    { id: "io",           label: "io Products",      sector: "app" },
    { id: "kpmg",         label: "KPMG",             sector: "app" },
    { id: "snowflake",    label: "Snowflake",        sector: "app" },
    { id: "sbenergy",     label: "SB Energy",        sector: "app" },
    { id: "novo",         label: "Novo Nordisk",     sector: "app" },
    { id: "noetra",       label: "Noetra",           sector: "app", jp: true },
    { id: "sony",         label: "ソニーG",           sector: "app", jp: true },
    { id: "nec",          label: "NEC",              sector: "app", jp: true },
    { id: "honda",        label: "ホンダ",            sector: "app", jp: true },
    // 投資家・ファンド
    { id: "mgx",          label: "MGX",              sector: "invest" },
    { id: "softbank",     label: "ソフトバンクG",     sector: "invest", jp: true },
    { id: "mufg",         label: "MUFG",             sector: "invest", jp: true },
    { id: "catl",         label: "CATL",             sector: "invest" },
    { id: "meti",         label: "経産省",            sector: "invest", jp: true }
  ],
  edges: [
    // ── 出資・資金調達 (invest) ──
    // OpenAI
    { from: "microsoft", to: "openai", type: "invest", threads: ["labs"], amount: 130,
      label: "累計130億ドル出資・OpenAI PBCの約27%を保有（評価額5,000億ドル）", date: "2025-10",
      source: "https://www.cnbc.com/2025/10/28/open-ai-for-profit-microsoft.html" },
    { from: "nvidia", to: "openai", type: "invest", threads: ["labs"], amount: 300,
      label: "26年2月ラウンドで300億ドル出資（25年9月に最大1,000億ドルの投資意向も表明）", date: "2026-02",
      source: "https://techcrunch.com/2026/02/27/openai-raises-110b-in-one-of-the-largest-private-funding-rounds-in-history/" },
    { from: "amazon", to: "openai", type: "invest", threads: ["labs"], amount: 500,
      label: "26年2月ラウンドで500億ドル出資", date: "2026-02",
      source: "https://techcrunch.com/2026/02/27/openai-raises-110b-in-one-of-the-largest-private-funding-rounds-in-history/" },
    { from: "softbank", to: "openai", type: "invest", threads: ["labs", "japan"], amount: 700,
      label: "25年の400億ドルラウンド主導＋26年2月ラウンドで300億ドル出資", date: "2026-02",
      source: "https://techcrunch.com/2026/02/27/openai-raises-110b-in-one-of-the-largest-private-funding-rounds-in-history/" },
    { from: "mgx", to: "openai", type: "invest", threads: ["labs"], amount: null,
      label: "1,220億ドル調達ラウンドに参加（金額非公表）・Stargate共同出資者", date: "2026-07",
      source: "https://www.cnbc.com/2026/07/01/mgx-ai-fund-uae-49-billion.html" },
    // Anthropic
    { from: "google", to: "anthropic", type: "invest", threads: ["labs"], amount: 400,
      label: "最大400億ドル出資（即時100億＋業績連動300億）", date: "2026-04",
      source: "https://techcrunch.com/2026/04/24/google-to-invest-up-to-40b-in-anthropic-in-cash-and-compute/" },
    { from: "microsoft", to: "anthropic", type: "invest", threads: ["labs"], amount: 50,
      label: "50億ドル出資（評価額約3,500億ドル）", date: "2025-11",
      source: "https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/" },
    { from: "nvidia", to: "anthropic", type: "invest", threads: ["labs"], amount: 100,
      label: "最大100億ドル出資", date: "2025-11",
      source: "https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/" },
    { from: "amazon", to: "anthropic", type: "invest", threads: ["labs"], amount: 330,
      label: "累計80億ドル出資（24/11）＋最大250億ドルの追加投資（26/4）", date: "2026-04",
      source: "https://www.cnbc.com/2026/04/20/amazon-invest-up-to-25-billion-in-anthropic-part-of-ai-infrastructure.html" },
    { from: "mgx", to: "anthropic", type: "invest", threads: ["labs"], amount: null,
      label: "シリーズH（650億ドル・評価額9,650億ドル）に参加（金額非公表）", date: "2026-07",
      source: "https://www.cnbc.com/2026/07/01/mgx-ai-fund-uae-49-billion.html" },
    { from: "samsung", to: "anthropic", type: "invest", threads: ["labs", "semi"], amount: null,
      label: "シリーズH（650億ドル・評価額9,650億ドル）の戦略投資家。後にFoundry製造契約へ発展", date: "2026-05",
      source: "https://www.koreaherald.com/article/10797311" },
    { from: "skhynix", to: "anthropic", type: "invest", threads: ["labs", "semi"], amount: null,
      label: "シリーズH（650億ドル）に参加（金額非公表）。HBMサプライヤーとしての資本関係", date: "2026-05",
      source: "https://www.koreaherald.com/article/10797311" },
    { from: "micron", to: "anthropic", type: "invest", threads: ["labs", "semi"], amount: null,
      label: "シリーズH（650億ドル）に参加（金額非公表）。メモリ大手のフロンティアラボ出資", date: "2026-05",
      source: "https://www.koreaherald.com/article/10797311" },
    // xAI / DeepSeek / Mistral
    { from: "nvidia", to: "xai", type: "invest", threads: ["labs"], amount: null,
      label: "シリーズE 200億ドル（評価額2,300億ドル）に参加（金額非公表）", date: "2026-01",
      source: "https://techcrunch.com/2026/01/06/xai-says-it-raised-20b-in-series-e-funding/" },
    { from: "mgx", to: "xai", type: "invest", threads: ["labs"], amount: null,
      label: "シリーズE 200億ドルに参加（金額非公表）", date: "2026-01",
      source: "https://techcrunch.com/2026/01/06/xai-says-it-raised-20b-in-series-e-funding/" },
    { from: "tencent", to: "deepseek", type: "invest", threads: ["china", "labs"], amount: 74,
      label: "初の外部調達74億ドルを主導（評価額最大590億ドル）", date: "2026-06",
      source: "https://www.bloomberg.com/news/articles/2026-06-03/deepseek-close-to-sealing-7-billion-funding-in-historic-ai-deal" },
    { from: "catl", to: "deepseek", type: "invest", threads: ["china", "labs"], amount: null,
      label: "テンセント主導の初外部調達74億ドルに主要投資家として参加（金額非公表）", date: "2026-06",
      source: "https://www.bloomberg.com/news/articles/2026-06-03/deepseek-close-to-sealing-7-billion-funding-in-historic-ai-deal" },
    { from: "asml", to: "mistral", type: "invest", threads: ["labs", "semi"], amount: 14,
      label: "シリーズC 17億ユーロを主導（13億ユーロ・約11%取得、評価額117億ユーロ）", date: "2025-09",
      source: "https://www.cnbc.com/2025/09/09/ai-firm-mistral-valued-at-14-billion-as-asml-takes-major-stake.html" },
    // 日本・インフラ
    { from: "nvidia", to: "sakana", type: "invest", threads: ["japan"], amount: null,
      label: "シリーズAに出資（金額非公表・日本でのAI研究開発で協力）", date: "2024-09",
      source: "https://sakana.ai/series-a-jp/" },
    { from: "mufg", to: "sakana", type: "invest", threads: ["japan"], amount: null,
      label: "シリーズB約200億円に出資（企業価値約4,000億円）", date: "2025-11",
      source: "https://ledge.ai/articles/sakana_ai_series_b_200oku_fundraising" },
    { from: "meta", to: "scaleai", type: "invest", threads: ["talent"], amount: 143,
      label: "143億ドルで49%取得", date: "2025-06",
      source: "https://www.cnbc.com/2025/06/12/scale-ai-founder-wang-announces-exit-for-meta-part-of-14-billion-deal.html" },
    { from: "nvidia", to: "nebius", type: "invest", threads: ["compute", "labs"], amount: 20,
      label: "20億ドル出資。Nebiusは2030年末までにNVIDIAシステム5GW超の展開を目指す", date: "2026-03",
      source: "https://nvidianews.nvidia.com/news/nvidia-and-nebius-partner-to-scale-full-stack-ai-cloud" },
    { from: "softbank", to: "noetra", type: "invest", threads: ["japan"], amount: null,
      label: "44社連合の中核出資者として国産AI基盤会社Noetraを設立主導", date: "2026-07",
      source: "https://response.jp/article/2026/07/17/414143.html" },
    { from: "sony", to: "noetra", type: "invest", threads: ["japan"], amount: null,
      label: "ソフトバンク・NEC・ホンダと並ぶ中核4社の一角としてNoetraに出資", date: "2026-07",
      source: "https://response.jp/article/2026/07/17/414143.html" },
    { from: "nec", to: "noetra", type: "invest", threads: ["japan"], amount: null,
      label: "中核4社の一角としてNoetraに出資。国産マルチモーダル基盤の開発を共同推進", date: "2026-07",
      source: "https://response.jp/article/2026/07/17/414143.html" },
    { from: "honda", to: "noetra", type: "invest", threads: ["japan"], amount: null,
      label: "中核4社の一角としてNoetraに出資。フィジカルAI（ロボット・自動運転）の実需側", date: "2026-07",
      source: "https://response.jp/article/2026/07/17/414143.html" },
    { from: "meti", to: "noetra", type: "invest", threads: ["japan"], amount: 65,
      label: "初年度3,873億円・5年で最大約1兆円（約65億ドル相当）を支援", date: "2026-07",
      source: "https://response.jp/article/2026/07/17/414143.html" },
    { from: "meti", to: "micron", type: "invest", threads: ["japan", "semi"], amount: 35,
      label: "広島工場拡張に最大5,360億円（約35億ドル相当）を助成（生産能力5,000億＋R&D 360億）", date: "2026-07",
      source: "https://jp.micron.com/about/press/news/micron-breaks-ground-on-hiroshima-cleanroom-to-support-advanced-memory-for-ai" },

    // ── 提携・供給契約 (partner) ──
    // OpenAI コンピュート網
    { from: "openai", to: "microsoft", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "Azure 2,500億ドル追加購入契約（25/10）。26/4に独占提携・収益分配は終了", date: "2026-04",
      source: "https://www.forbes.com/sites/aliciapark/2026/04/27/openai-and-microsoft-end-exclusive-partnership-and-revenue-sharing/" },
    { from: "openai", to: "oracle", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "Stargate 4.5GW拡張＋OCIでフロンティアモデル提供（Universal Credits）", date: "2026-06",
      source: "https://openai.com/index/openai-on-oracle-cloud/" },
    { from: "openai", to: "softbank", type: "partner", threads: ["compute", "japan"], flow: "計算資源",
      label: "Stargate（最大5,000億ドル）共同出資＋合弁SB OAI JapanでCristal intelligence展開", date: "2025-11",
      source: "https://group.softbank/en/news/press/20251105" },
    { from: "openai", to: "amd", type: "partner", threads: ["compute", "semi"], flow: "計算資源",
      label: "Instinct GPU 6GW供給契約＋最大1.6億株のワラント付与", date: "2025-10",
      source: "https://openai.com/index/openai-amd-strategic-partnership/" },
    { from: "openai", to: "broadcom", type: "partner", threads: ["compute", "semi"], flow: "技術",
      label: "独自推論チップ「Jalapeño」を共同開発（10GW規模）。初期展開2026年後半、完了目標2029年末", date: "2026-06",
      source: "https://techcrunch.com/2026/06/24/openai-unveils-its-first-custom-chip-built-by-broadcom/" },
    { from: "openai", to: "tsmc", type: "partner", threads: ["semi"], flow: "技術",
      label: "Jalapeño（Broadcom共同設計）の製造をTSMCに委託", date: "2026-06",
      source: "https://techcrunch.com/2026/06/24/openai-unveils-its-first-custom-chip-built-by-broadcom/" },
    { from: "openai", to: "cerebras", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "超低遅延推論向けに750MWのAIコンピュートを段階導入（2028年まで）", date: "2026-01",
      source: "https://openai.com/index/cerebras-partnership/" },
    { from: "openai", to: "amazon", type: "partner", threads: ["compute", "semi"], flow: "計算資源",
      label: "AWSでStateful Runtime共同開発・Frontier第三者配信。Trainium約2GWを含む複数年提携", date: "2026-04",
      source: "https://convergedigest.com/amazon-q1-2026-aws-surges-28-as-custom-ai-chips-top-20b-run-rate/" },
    { from: "openai", to: "snowflake", type: "partner", threads: [], flow: "販売",
      label: "Snowflake Cortex AI／IntelligenceでOpenAIモデルを提供する複数年・2億ドルの企業データ向け提携", date: "2026-02",
      source: "https://openai.com/index/snowflake-partnership/" },
    { from: "openai", to: "sbenergy", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "Stargateの一環。SB Energyがデータセンター／電力インフラを担い、OpenAIは米国Milam Countyの1.2GWデータセンターをリース", date: "2026-01",
      source: "https://openai.com/index/stargate-sb-energy-partnership/" },
    { from: "apple", to: "openai", type: "partner", threads: ["labs", "talent"], flow: "モデル", status: "reported",
      label: "2024年ChatGPT×iOS統合提携。io Products買収後に関係悪化、26/7にAppleが営業秘密訴訟", date: "2024-06",
      source: "https://techcrunch.com/2026/07/10/apple-sues-openai-over-alleged-trade-secret-theft/" },
    // Anthropic コンピュート網
    { from: "anthropic", to: "microsoft", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "Azureのコンピュート300億ドル分を購入コミット", date: "2025-11",
      source: "https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/" },
    { from: "anthropic", to: "microsoft", type: "partner", threads: ["semi", "compute"], flow: "技術", status: "negotiating",
      label: "Microsoft独自チップMaia 200でClaude推論を実行する契約を交渉中（報道）", date: "2026-05",
      source: "https://www.cnbc.com/2026/05/21/anthropic-microsoft-maia-200-ai-chip.html" },
    { from: "anthropic", to: "google", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "次世代TPU容量を複数GW規模で確保。2027年から順次稼働予定（Google CloudのTPU利用を拡張）", date: "2026-04",
      source: "https://www.anthropic.com/news/google-broadcom-partnership-compute" },
    { from: "anthropic", to: "broadcom", type: "partner", threads: ["compute", "semi"], flow: "技術",
      label: "カスタムAIアクセラレータの共同開発を含む大型コンピュート提携", date: "2026-05",
      source: "https://www.anthropic.com/news/google-broadcom-partnership-compute" },
    { from: "anthropic", to: "amazon", type: "partner", threads: ["compute", "semi"], flow: "計算資源",
      label: "AWS Trainium最大5GWの容量確保を含む超大型コンピュート契約（Trainium3出荷開始と同時期）", date: "2026-04",
      source: "https://convergedigest.com/amazon-q1-2026-aws-surges-28-as-custom-ai-chips-top-20b-run-rate/" },
    { from: "anthropic", to: "terawulf", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "20年・190億ドルのデータセンターリース（ケンタッキー州401MW、2027年後半稼働）", date: "2026-07",
      source: "https://siliconangle.com/2026/07/06/anthropic-inks-19b-ai-data-center-lease-terawulf/" },
    { from: "anthropic", to: "spacex", type: "partner", threads: ["compute"], flow: "計算資源", status: "reported",
      label: "SpaceX IPO目論見書で、2029年5月まで月額12.5億ドル（総額約450億ドル）のGPUコンピュート契約が開示", date: "2026-06",
      source: "https://mlq.ai/news/anthropic-signs-12-letters-of-intent-for-direct-data-center-leases-totaling-over-1-gw/" },
    { from: "anthropic", to: "samsung", type: "partner", threads: ["semi"], flow: "技術",
      label: "Samsung Foundry 2nm（SF2）でカスタムAI推論チップの製造委託契約", date: "2026-07",
      source: "https://www.koreaherald.com/article/10797311" },
    { from: "anthropic", to: "kpmg", type: "partner", threads: [], flow: "販売",
      label: "戦略提携: 従業員27.6万人規模でClaudeを全社統合", date: "2026-05",
      source: "https://www.anthropic.com/news" },
    { from: "openai", to: "novo", type: "partner", threads: [], flow: "販売",
      label: "全社AI戦略提携（創薬〜製造〜営業）", date: "2026-04",
      source: "https://www.cnbc.com/2026/04/14/novo-nordisk-openai-ai-drug-discovery-healthcare-nvo.html" },
    // モデル配信・中国勢
    { from: "apple", to: "google", type: "partner", threads: ["labs"], flow: "モデル",
      label: "Gemini搭載の新Siri（年約10億ドルの契約）", date: "2026-01",
      source: "https://www.cnbc.com/2026/01/12/apple-google-ai-siri-gemini.html" },
    { from: "microsoft", to: "moonshot", type: "partner", threads: ["china"], flow: "モデル",
      label: "GitHub CopilotがKimi K2.7 Codeを採用（Copilot初のオープンウェイトモデル）", date: "2026-07",
      source: "https://github.blog/changelog/2026-07-01-kimi-k2-7-is-now-available-in-github-copilot/" },
    { from: "xai", to: "amazon", type: "partner", threads: ["compute", "labs"], flow: "モデル",
      label: "Grok 4.3をAmazon Bedrockで一般提供（100万トークン・米ラボ最安値水準）", date: "2026-06",
      source: "https://aws.amazon.com/about-aws/whats-new/2026/06/grok-amazon-bedrock/" },
    { from: "huawei", to: "deepseek", type: "partner", threads: ["china", "semi", "compute"], flow: "計算資源", status: "reported",
      label: "中国の国家AIデータセンター網（2,950億ドル計画）で国産チップ80%使用方針。Huawei Ascend等が候補", date: "2026-06",
      source: "https://www.bloomberg.com/news/articles/2026-06-09/china-prepares-295-billion-plan-to-fund-nationwide-ai-buildout" },
    { from: "alibaba", to: "moonshot", type: "partner", threads: ["china"], flow: "モデル", status: "reported",
      label: "中国オープンウェイト勢（Qwen・Kimi・DeepSeek）として並走。規制対応でも同調（擬人化AI規制等）", date: "2026-07",
      source: "https://qz.com/bytedance-alibaba-ai-companion-chatbot-china-rules-070626" },
    { from: "bytedance", to: "alibaba", type: "partner", threads: ["china"], flow: "モデル", status: "reported",
      label: "CAC擬人化AI規制（26/7/15施行）に伴いDoubao・Qwenがコンパニオン機能を同時停止", date: "2026-07",
      source: "https://qz.com/bytedance-alibaba-ai-companion-chatbot-china-rules-070626" },
    // 半導体サプライチェーン
    { from: "nvidia", to: "skhynix", type: "partner", threads: ["semi"], flow: "技術",
      label: "次世代HBM共同開発の複数年技術提携（AI Factory向け）", date: "2026-06",
      source: "https://nvidianews.nvidia.com/news/sk-hynix-ai-factory" },
    { from: "nvidia", to: "microsoft", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "AzureへGrace Blackwell GB200、DGX Cloud／Microsoft Fabric連携、NVIDIA AIマイクロサービスを展開", date: "2024-03",
      source: "https://nvidianews.nvidia.com/news/microsoft-nvidia-generative-ai-enterprises" },
    { from: "nvidia", to: "google", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "Google CloudがGrace BlackwellとDGX Cloudを採用。Vertex AI、NIM、JAXなどでAI基盤を統合", date: "2024-03",
      source: "https://nvidianews.nvidia.com/news/google-cloud-ai-development" },
    { from: "nvidia", to: "amazon", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "AWSでBlackwell GPU、DGX Cloud、SageMakerとNIMを展開。研究用スパコンProject Ceibaも共同構築", date: "2024-03",
      source: "https://nvidianews.nvidia.com/news/aws-nvidia-generative-ai-innovation" },
    { from: "nvidia", to: "oracle", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "OCI上でNVIDIA AI EnterpriseとNIMをネイティブ提供。AI推論とOracle Database 23aiを統合", date: "2025-03",
      source: "https://nvidianews.nvidia.com/news/oracle-and-nvidia-collaborate-to-help-enterprises-accelerate-agentic-ai-inference" },
    { from: "nvidia", to: "nebius", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "フルスタックAIクラウドを共同開発。Nebiusは2030年末までにNVIDIAシステム5GW超を目指す", date: "2026-03",
      source: "https://nvidianews.nvidia.com/news/nvidia-and-nebius-partner-to-scale-full-stack-ai-cloud" },
    { from: "google", to: "intel", type: "partner", threads: ["semi"], flow: "技術", status: "reported",
      label: "Intel FoundryにTPU 300万個超を発注（2028年納入目標・報道）", date: "2026-06",
      source: "https://www.techtimes.com/articles/318143/20260610/chip-supply-shifts-tsmc-googles-reported-intel-tpu-order-lifts-foundry-doubts-remain.htm" },
    { from: "nvidia", to: "tsmc", type: "partner", threads: ["semi"], flow: "技術",
      label: "AI GPUの主要製造委託（TSMCはアリゾナ追加1,000億ドル投資でAI需要に対応）", date: "2026-07",
      source: "https://finance.yahoo.com/markets/stocks/articles/tsmc-q2-2026-earnings-record-112109987.html" },
    { from: "asml", to: "intel", type: "partner", threads: ["semi"], flow: "技術",
      label: "High-NA EUV（NA0.55）で業界初の商用ロジック量産出荷（Intel 18A・歩留まり約85%）", date: "2026-07",
      source: "https://www.globenewswire.com/news-release/2026/07/15/3327453/0/en/High-NA-EUV-reaches-new-readiness-milestone-with-first-high-volume-Logic-product.html" },
    { from: "asml", to: "mistral", type: "partner", threads: ["semi"], flow: "技術",
      label: "リソグラフィ製品群へのAIモデル適用で長期協業", date: "2025-09",
      source: "https://www.asml.com/en/news/press-releases/2025/asml-mistral-ai-enter-strategic-partnership" },
    { from: "qualcomm", to: "meta", type: "partner", threads: ["semi", "compute"], flow: "技術",
      label: "HBCアーキテクチャ採用のAIアクセラレータを複数世代で長期戦略提携（AI250/AI300、2027年〜）", date: "2026-06",
      source: "https://www.servethehome.com/qualcomm-investor-day-2026-data-center-announcements-cpus-ai-accelerators-and-more/" },
    { from: "qualcomm", to: "microsoft", type: "partner", threads: ["semi", "compute"], flow: "技術",
      label: "AzureがQualcomm AI250・AI300アクセラレータの導入を確認（HBM不要のHBC設計）", date: "2026-06",
      source: "https://www.servethehome.com/qualcomm-investor-day-2026-data-center-announcements-cpus-ai-accelerators-and-more/" },
    // ネオクラウド・日本
    { from: "meta", to: "nebius", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "5年270億ドルのAIインフラ契約（うち120億ドルはNvidia Vera Rubin GPU展開）", date: "2026-07",
      source: "https://dentro.de/ai/news/" },
    { from: "reflectionai", to: "nebius", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "10億ドル超・2029年までのコンピュート契約でNvidia GB300 GPUを確保", date: "2026-07",
      source: "https://techcrunch.com/2026/07/14/reflection-inks-1b-compute-deal-with-nebius/" },
    { from: "reflectionai", to: "spacex", type: "partner", threads: ["compute"], flow: "計算資源",
      label: "2026年6月に月額1.5億ドル規模のコンピュート契約を締結（Nebius契約に先行）", date: "2026-06",
      source: "https://techcrunch.com/2026/07/14/reflection-inks-1b-compute-deal-with-nebius/" },
    { from: "nvidia", to: "noetra", type: "partner", threads: ["japan", "compute"], flow: "計算資源",
      label: "次世代GPU「Rubin」約2.75万基・CPU「Vera」約1.375万基を独占供給（2028年6月稼働・大阪堺市）", date: "2026-07",
      source: "https://response.jp/article/2026/07/17/414143.html" },
    { from: "rapidus", to: "ibm", type: "partner", threads: ["japan", "semi"], flow: "技術",
      label: "2nmプロセス開発＋チップレット量産技術の戦略提携", date: "2023-12",
      source: "https://www.imagazine.co.jp/ibm-rapidus-partnership/" },
    { from: "sakana", to: "google", type: "partner", threads: ["japan"], flow: "モデル",
      label: "戦略的パートナーシップ（研究開発にGeminiを活用）", date: "2026",
      source: "https://www.sbbit.jp/article/cont1/179274" },
    { from: "micron", to: "meti", type: "partner", threads: ["japan", "semi"], flow: "技術",
      label: "広島工場に新クリーンルーム着工（総投資1.5兆円）。HBM・EUV次世代DRAM増産、2028年後半設備導入", date: "2026-07",
      source: "https://jp.micron.com/about/press/news/micron-breaks-ground-on-hiroshima-cleanroom-to-support-advanced-memory-for-ai" },

    // ── 買収・合併 (ma) ──
    { from: "spacex", to: "xai", type: "ma", threads: ["labs"],
      label: "SpaceXがxAIを吸収合併（xAI評価額2,500億ドル・合併後評価はIPO時1.75兆ドル規模）", date: "2026-02",
      source: "https://www.cnbc.com/2026/02/03/musk-xai-spacex-biggest-merger-ever.html" },
    { from: "spacex", to: "cursor", type: "ma", threads: ["talent"],
      label: "Cursor開発元Anysphereを600億ドルで買収（VC支援スタートアップ史上最大）", date: "2026-06",
      source: "https://www.cnbc.com/2026/06/16/spacex-spcx-cursor-acquisition-ipo.html" },
    { from: "anthropic", to: "stainless", type: "ma", threads: ["talent"],
      label: "SDK自動生成のStainlessを3億ドル超で買収", date: "2026-05",
      source: "https://techcrunch.com/2026/05/18/anthropic-has-acquired-the-dev-tools-startup-used-by-openai-google-and-cloudflare/" },
    { from: "anthropic", to: "coefficient", type: "ma", threads: ["talent"],
      label: "Coefficient Bioを約4億ドルで買収（医療AI参入）", date: "2026-04",
      source: "https://techstartups.com/2026/04/03/top-tech-news-today-april-3-2026/" },
    { from: "openai", to: "astral", type: "ma", threads: ["talent"],
      label: "Pythonツール（uv/ruff）のAstralを買収・Codex強化", date: "2026-03",
      source: "https://blog.tahababa.com/2026/03/march-21-2026-ai-funding-innovation.html" },
    { from: "openai", to: "io", type: "ma", threads: ["talent"],
      label: "Jony Iveのio Productsを約64億ドルで買収しハードウェア参入（26/7にAppleが提訴）", date: "2025-05",
      source: "https://techcrunch.com/2026/07/10/apple-sues-openai-over-alleged-trade-secret-theft/" },
    { from: "qualcomm", to: "tenstorrent", type: "ma", threads: ["semi"], status: "negotiating",
      label: "80〜100億ドルで買収交渉中（26/6報道・未確定）", date: "2026-06",
      source: "https://www.theregister.com/systems/2026/06/16/qualcomm-said-to-be-circling-ai-chip-biz-tenstorrent-in-10b-risc-v-power-play/5256084" },

    // ── 人材移籍 (talent) ── 人物単位で1エッジ
    { from: "google", to: "anthropic", type: "talent", threads: ["talent"], person: "John Jumper",
      label: "2024年ノーベル化学賞受賞者（AlphaFold2開発主導）。9年弱在籍したDeepMindからAnthropicへ", date: "2026-06",
      source: "https://techcrunch.com/2026/06/20/nobel-laureate-john-jumper-is-leaving-deepmind-for-rival-anthropic/" },
    { from: "google", to: "anthropic", type: "talent", threads: ["talent"], person: "Jonas Adler・Alexander Pritzel",
      label: "Gemini開発の中核を担った研究者2名がAnthropicへ移籍", date: "2026-06",
      source: "https://www.bloomberg.com/news/articles/2026-06-24/google-poised-to-lose-two-more-high-profile-ai-staffers-to-anthropic" },
    { from: "google", to: "openai", type: "talent", threads: ["talent"], person: "Noam Shazeer",
      label: "『Attention Is All You Need』共著者・Gemini共同リード。27億ドルで呼び戻されてから22か月でOpenAIへ", date: "2026-06",
      source: "https://www.cnbc.com/2026/06/18/google-gemini-co-lead-noam-shazeer-leaves-for-openai.html" },
    { from: "scaleai", to: "meta", type: "talent", threads: ["talent"], person: "Alexandr Wang",
      label: "Scale AI創業者。Metaの超知能ラボ（Superintelligence Lab）責任者に就任", date: "2025-06",
      source: "https://www.cnbc.com/2025/06/12/scale-ai-founder-wang-announces-exit-for-meta-part-of-14-billion-deal.html" },
    { from: "meta", to: "ami", type: "talent", threads: ["talent"], person: "Yann LeCun",
      label: "Meta元チーフAIサイエンティスト。独立してAMI Labsを創業（シード10.3億ドル・欧州最大）", date: "2026-03",
      source: "https://www.crescendo.ai/news/latest-ai-news-and-updates" },
    { from: "apple", to: "openai", type: "talent", threads: ["talent"], person: "Tang Tan",
      label: "元Apple上級副社長。OpenAIハードウェア責任者として移籍後、26/7にAppleが営業秘密訴訟で名指し", date: "2025",
      source: "https://techcrunch.com/2026/07/10/apple-sues-openai-over-alleged-trade-secret-theft/" },
    { from: "openai", to: "anthropic", type: "talent", threads: ["talent", "semi"], person: "Clive Chan",
      label: "OpenAIカスタムチップチーム初期メンバー。Anthropicの独自チップ設計を加速するため移籍", date: "2026",
      source: "https://www.koreaherald.com/article/10797311" },
    { from: "google", to: "reflectionai", type: "talent", threads: ["talent", "labs"], person: "DeepMind卒業生創業チーム",
      label: "元Google DeepMind研究者が2024年にReflection AIを創業（評価額80億ドル・累計調達26億ドル）", date: "2024",
      source: "https://techcrunch.com/2026/07/14/reflection-inks-1b-compute-deal-with-nebius/" }
  ]
};
