// AI業界 相関図データ
// map.html が描画する。毎週土曜の定期実行で直近1週間のニュースから追記される。
// エッジ type: invest(出資・資金調達) / partner(提携・供給契約) / talent(人材移籍) / ma(買収・合併)
// 全エッジに source（出典URL）必須。古い関係も履歴として残す（削除しない）。
window.RELATIONS = {
  updated: "2026-07-17",
  nodes: [
    { id: "openai",      label: "OpenAI",            group: "ai_lab" },
    { id: "anthropic",   label: "Anthropic",         group: "ai_lab" },
    { id: "xai",         label: "xAI",               group: "ai_lab" },
    { id: "deepseek",    label: "DeepSeek",          group: "ai_lab" },
    { id: "mistral",     label: "Mistral AI",        group: "ai_lab" },
    { id: "ami",         label: "AMI Labs",          group: "ai_lab" },
    { id: "microsoft",   label: "Microsoft",         group: "bigtech" },
    { id: "google",      label: "Google",            group: "bigtech" },
    { id: "amazon",      label: "Amazon",            group: "bigtech" },
    { id: "meta",        label: "Meta",              group: "bigtech" },
    { id: "apple",       label: "Apple",             group: "bigtech" },
    { id: "ibm",         label: "IBM",               group: "bigtech" },
    { id: "tencent",     label: "Tencent",           group: "bigtech" },
    { id: "nvidia",      label: "NVIDIA",            group: "chip" },
    { id: "amd",         label: "AMD",               group: "chip" },
    { id: "broadcom",    label: "Broadcom",          group: "chip" },
    { id: "intel",       label: "Intel",             group: "chip" },
    { id: "qualcomm",    label: "Qualcomm",          group: "chip" },
    { id: "tsmc",        label: "TSMC",              group: "chip" },
    { id: "skhynix",     label: "SK hynix",          group: "chip" },
    { id: "asml",        label: "ASML",              group: "chip" },
    { id: "cerebras",    label: "Cerebras",          group: "chip" },
    { id: "tenstorrent", label: "Tenstorrent",       group: "chip" },
    { id: "oracle",      label: "Oracle",            group: "cloud" },
    { id: "spacex",      label: "SpaceX",            group: "other" },
    { id: "scaleai",     label: "Scale AI",          group: "other" },
    { id: "cursor",      label: "Cursor (Anysphere)", group: "other" },
    { id: "stainless",   label: "Stainless",         group: "other" },
    { id: "coefficient", label: "Coefficient Bio",   group: "other" },
    { id: "astral",      label: "Astral",            group: "other" },
    { id: "io",          label: "io Products",       group: "other" },
    { id: "kpmg",        label: "KPMG",              group: "other" },
    { id: "novo",        label: "Novo Nordisk",      group: "other" },
    { id: "mgx",         label: "MGX",               group: "vc" },
    { id: "softbank",    label: "ソフトバンクG",      group: "jp" },
    { id: "rapidus",     label: "Rapidus",           group: "jp" },
    { id: "sakana",      label: "Sakana AI",         group: "jp" },
    { id: "mufg",        label: "MUFG",              group: "jp" }
  ],
  edges: [
    // ── 出資・資金調達 (invest) ──
    { from: "microsoft", to: "openai", type: "invest",
      label: "累計130億ドル出資・OpenAI PBCの約27%を保有（評価額5,000億ドル）", date: "2025-10",
      source: "https://www.cnbc.com/2025/10/28/open-ai-for-profit-microsoft.html" },
    { from: "nvidia", to: "openai", type: "invest",
      label: "26年2月ラウンドで300億ドル出資（25年9月に最大1,000億ドルの投資意向も表明）", date: "2026-02",
      source: "https://techcrunch.com/2026/02/27/openai-raises-110b-in-one-of-the-largest-private-funding-rounds-in-history/" },
    { from: "amazon", to: "openai", type: "invest",
      label: "26年2月ラウンドで500億ドル出資", date: "2026-02",
      source: "https://techcrunch.com/2026/02/27/openai-raises-110b-in-one-of-the-largest-private-funding-rounds-in-history/" },
    { from: "softbank", to: "openai", type: "invest",
      label: "26年2月ラウンドで300億ドル出資（25年の400億ドルラウンドも主導）", date: "2026-02",
      source: "https://techcrunch.com/2026/02/27/openai-raises-110b-in-one-of-the-largest-private-funding-rounds-in-history/" },
    { from: "mgx", to: "openai", type: "invest",
      label: "1,220億ドル調達ラウンドに参加・Stargate共同出資者", date: "2026-07",
      source: "https://www.cnbc.com/2026/07/01/mgx-ai-fund-uae-49-billion.html" },
    { from: "google", to: "anthropic", type: "invest",
      label: "最大400億ドル出資（即時100億＋業績連動300億）", date: "2026-04",
      source: "https://techcrunch.com/2026/04/24/google-to-invest-up-to-40b-in-anthropic-in-cash-and-compute/" },
    { from: "microsoft", to: "anthropic", type: "invest",
      label: "50億ドル出資（評価額約3,500億ドル）", date: "2025-11",
      source: "https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/" },
    { from: "nvidia", to: "anthropic", type: "invest",
      label: "最大100億ドル出資", date: "2025-11",
      source: "https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/" },
    { from: "amazon", to: "anthropic", type: "invest",
      label: "累計80億ドル出資（24/11）＋最大250億ドルの追加投資（26/4）", date: "2026-04",
      source: "https://www.cnbc.com/2026/04/20/amazon-invest-up-to-25-billion-in-anthropic-part-of-ai-infrastructure.html" },
    { from: "mgx", to: "anthropic", type: "invest",
      label: "シリーズH（650億ドル・評価額9,650億ドル）に参加", date: "2026-07",
      source: "https://www.cnbc.com/2026/07/01/mgx-ai-fund-uae-49-billion.html" },
    { from: "nvidia", to: "xai", type: "invest",
      label: "シリーズE 200億ドル（評価額2,300億ドル）に参加", date: "2026-01",
      source: "https://techcrunch.com/2026/01/06/xai-says-it-raised-20b-in-series-e-funding/" },
    { from: "mgx", to: "xai", type: "invest",
      label: "シリーズE 200億ドルに参加", date: "2026-01",
      source: "https://techcrunch.com/2026/01/06/xai-says-it-raised-20b-in-series-e-funding/" },
    { from: "tencent", to: "deepseek", type: "invest",
      label: "初の外部調達74億ドルを主導（評価額最大590億ドル）", date: "2026-06",
      source: "https://www.bloomberg.com/news/articles/2026-06-03/deepseek-close-to-sealing-7-billion-funding-in-historic-ai-deal" },
    { from: "asml", to: "mistral", type: "invest",
      label: "シリーズC 17億ユーロを主導（13億ユーロ・約11%取得、評価額117億ユーロ）", date: "2025-09",
      source: "https://www.cnbc.com/2025/09/09/ai-firm-mistral-valued-at-14-billion-as-asml-takes-major-stake.html" },
    { from: "nvidia", to: "sakana", type: "invest",
      label: "シリーズAに出資（日本でのAI研究開発で協力）", date: "2024-09",
      source: "https://sakana.ai/series-a-jp/" },
    { from: "mufg", to: "sakana", type: "invest",
      label: "シリーズB約200億円に出資（企業価値約4,000億円）", date: "2025-11",
      source: "https://ledge.ai/articles/sakana_ai_series_b_200oku_fundraising" },
    { from: "meta", to: "scaleai", type: "invest",
      label: "143億ドルで49%取得", date: "2025-06",
      source: "https://www.cnbc.com/2025/06/12/scale-ai-founder-wang-announces-exit-for-meta-part-of-14-billion-deal.html" },

    // ── 提携・供給契約 (partner) ──
    { from: "openai", to: "microsoft", type: "partner",
      label: "Azure 2,500億ドル追加購入契約（25/10）。26/4に独占提携・収益分配は終了", date: "2026-04",
      source: "https://www.forbes.com/sites/aliciapark/2026/04/27/openai-and-microsoft-end-exclusive-partnership-and-revenue-sharing/" },
    { from: "openai", to: "oracle", type: "partner",
      label: "Stargate 4.5GW拡張＋OCIでフロンティアモデル提供（Universal Credits）", date: "2026-06",
      source: "https://openai.com/index/openai-on-oracle-cloud/" },
    { from: "openai", to: "softbank", type: "partner",
      label: "Stargate（最大5,000億ドル）共同出資＋合弁SB OAI JapanでCristal intelligence展開", date: "2025-11",
      source: "https://group.softbank/en/news/press/20251105" },
    { from: "openai", to: "amd", type: "partner",
      label: "Instinct GPU 6GW供給契約＋最大1.6億株のワラント付与", date: "2025-10",
      source: "https://www.trendforce.com/news/2025/10/15/news-openai-ramps-up-global-compute-power-with-nvidia-amd-and-broadcom-securing-26-gw-of-ai-infrastructure/" },
    { from: "openai", to: "broadcom", type: "partner",
      label: "カスタムAIチップ10GWを共同開発（2029年までに展開）", date: "2025-10",
      source: "https://www.nbcnews.com/business/business-news/openai-taps-broadcom-build-first-ai-processor-latest-chip-deal-rcna237300" },
    { from: "openai", to: "cerebras", type: "partner",
      label: "推論向けチップ供給契約", date: "2026-01",
      source: "https://www.cnbc.com/2026/01/16/openai-chip-deal-with-cerebras-adds-to-roster-of-nvidia-amd-broadcom.html" },
    { from: "anthropic", to: "microsoft", type: "partner",
      label: "Azureのコンピュート300億ドル分を購入コミット", date: "2025-11",
      source: "https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/" },
    { from: "anthropic", to: "google", type: "partner",
      label: "Google Cloud経由でTPU 5GW分を5年間利用", date: "2026-04",
      source: "https://techcrunch.com/2026/04/24/google-to-invest-up-to-40b-in-anthropic-in-cash-and-compute/" },
    { from: "anthropic", to: "broadcom", type: "partner",
      label: "大型コンピュート提携", date: "2026-05",
      source: "https://www.anthropic.com/news/google-broadcom-partnership-compute" },
    { from: "anthropic", to: "kpmg", type: "partner",
      label: "戦略提携: 従業員27.6万人規模でClaudeを全社統合", date: "2026-05",
      source: "https://www.anthropic.com/news" },
    { from: "openai", to: "novo", type: "partner",
      label: "全社AI戦略提携（創薬〜製造〜営業）", date: "2026-04",
      source: "https://www.cnbc.com/2026/04/14/novo-nordisk-openai-ai-drug-discovery-healthcare-nvo.html" },
    { from: "apple", to: "google", type: "partner",
      label: "Gemini搭載の新Siri（年約10億ドルの契約）", date: "2026-01",
      source: "https://www.cnbc.com/2026/01/12/apple-google-ai-siri-gemini.html" },
    { from: "nvidia", to: "skhynix", type: "partner",
      label: "次世代HBM共同開発の複数年技術提携", date: "2026-06",
      source: "https://nvidianews.nvidia.com/news/sk-hynix-ai-factory" },
    { from: "google", to: "intel", type: "partner",
      label: "Intel FoundryにTPU 300万個超を発注（2028年納入目標・報道）", date: "2026-06",
      source: "https://www.techtimes.com/articles/318143/20260610/chip-supply-shifts-tsmc-googles-reported-intel-tpu-order-lifts-foundry-doubts-remain.htm" },
    { from: "nvidia", to: "tsmc", type: "partner",
      label: "AI GPUの主要製造委託（TSMCはアリゾナ追加1,000億ドル投資でAI需要に対応）", date: "2026-07",
      source: "https://finance.yahoo.com/markets/stocks/articles/tsmc-q2-2026-earnings-record-112109987.html" },
    { from: "rapidus", to: "ibm", type: "partner",
      label: "2nmプロセス開発＋チップレット量産技術の戦略提携", date: "2023-12",
      source: "https://www.imagazine.co.jp/ibm-rapidus-partnership/" },
    { from: "sakana", to: "google", type: "partner",
      label: "戦略的パートナーシップ（研究開発にGeminiを活用）", date: "2026",
      source: "https://www.sbbit.jp/article/cont1/179274" },
    { from: "asml", to: "mistral", type: "partner",
      label: "リソグラフィ製品群へのAIモデル適用で長期協業", date: "2025-09",
      source: "https://www.asml.com/en/news/press-releases/2025/asml-mistral-ai-enter-strategic-partnership" },

    // ── 買収・合併 (ma) ──
    { from: "spacex", to: "xai", type: "ma",
      label: "SpaceXがxAIを吸収合併（xAI評価額2,500億ドル・合併後1.25兆ドル、26/6にIPO）", date: "2026-02",
      source: "https://www.cnbc.com/2026/02/03/musk-xai-spacex-biggest-merger-ever.html" },
    { from: "spacex", to: "cursor", type: "ma",
      label: "Cursor開発元Anysphereを600億ドルで買収（VC支援スタートアップ史上最大）", date: "2026-06",
      source: "https://www.cnbc.com/2026/06/16/spacex-spcx-cursor-acquisition-ipo.html" },
    { from: "anthropic", to: "stainless", type: "ma",
      label: "SDK自動生成のStainlessを3億ドル超で買収", date: "2026-05",
      source: "https://techcrunch.com/2026/05/18/anthropic-has-acquired-the-dev-tools-startup-used-by-openai-google-and-cloudflare/" },
    { from: "anthropic", to: "coefficient", type: "ma",
      label: "Coefficient Bioを約4億ドルで買収（医療AI参入）", date: "2026-04",
      source: "https://techstartups.com/2026/04/03/top-tech-news-today-april-3-2026/" },
    { from: "openai", to: "astral", type: "ma",
      label: "Pythonツール（uv/ruff）のAstralを買収・Codex強化", date: "2026-03",
      source: "https://blog.tahababa.com/2026/03/march-21-2026-ai-funding-innovation.html" },
    { from: "openai", to: "io", type: "ma",
      label: "Jony Iveのio Productsを買収しハードウェア参入（この関係を巡り26/7にAppleが提訴）", date: "2025-05",
      source: "https://techcrunch.com/2026/07/10/apple-sues-openai-over-alleged-trade-secret-theft/" },
    { from: "qualcomm", to: "tenstorrent", type: "ma",
      label: "80〜100億ドルで買収交渉中（26/6報道・未確定）", date: "2026-06",
      source: "https://www.theregister.com/systems/2026/06/16/qualcomm-said-to-be-circling-ai-chip-biz-tenstorrent-in-10b-risc-v-power-play/5256084" },

    // ── 人材移籍 (talent) ──
    { from: "google", to: "anthropic", type: "talent",
      label: "John Jumper（ノーベル化学賞）らDeepMind研究者が相次ぎ移籍（26/6にAdler・Pritzelも）", date: "2026-06",
      source: "https://techcrunch.com/2026/06/20/nobel-laureate-john-jumper-is-leaving-deepmind-for-rival-anthropic/" },
    { from: "google", to: "openai", type: "talent",
      label: "Gemini共同リード Noam Shazeer が移籍", date: "2026-06",
      source: "https://www.cnbc.com/2026/06/18/google-gemini-co-lead-noam-shazeer-leaves-for-openai.html" },
    { from: "scaleai", to: "meta", type: "talent",
      label: "創業者 Alexandr Wang がMeta超知能ラボ責任者に", date: "2025-06",
      source: "https://www.cnbc.com/2025/06/12/scale-ai-founder-wang-announces-exit-for-meta-part-of-14-billion-deal.html" },
    { from: "meta", to: "ami", type: "talent",
      label: "元チーフサイエンティスト Yann LeCun が独立しAMI Labs創業（シード10.3億ドル・欧州最大）", date: "2026-03",
      source: "https://www.crescendo.ai/news/latest-ai-news-and-updates" }
  ]
};
